/** esbuild bundles of the DOM walker and the SF Symbol page scripts, shared by build-walker.ts and the freshness tests. */

import { build, type BuildOptions } from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const options: BuildOptions = {
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  legalComments: "none",
  logLevel: "silent",
};

async function bundle(entry: BuildOptions): Promise<string> {
  const result = await build({ ...options, ...entry });
  return result.outputFiles![0]!.text.trim();
}

export async function bundleWalker(): Promise<string> {
  return bundle({ entryPoints: [path.join(root, "src/dom/entry.ts")] });
}

/** A script that defines `window[global]` as one export of src/dom/symbols.ts. */
const symbolEntry = (name: string, global: string): BuildOptions => ({
  stdin: { contents: `import { ${name} } from "./symbols.ts";\nglobalThis.${global} = ${name};\n`, resolveDir: path.join(root, "src/dom"), sourcefile: `${global}.ts`, loader: "ts" },
});

export async function bundleSymbols(): Promise<{ collect: string; apply: string }> {
  const [collect, apply] = await Promise.all([bundle(symbolEntry("collectSymbols", "__sonobeCollectSymbols")), bundle(symbolEntry("applySymbols", "__sonobeApplySymbols"))]);
  return { collect, apply };
}

export function walkerModule(bundle: string): string {
  return `/**
 * Generated by packages/import/scripts/build-walker.ts from src/dom/walk.ts. Don't edit by hand:
 * run \`node packages/import/scripts/build-walker.ts\` after changing the walker.
 *
 * Evaluating WALKER_SOURCE in a page defines \`window.__sonobeCapture(options)\`, which resolves to a
 * DesignCapture (see src/dom/walk.ts).
 */

export const WALKER_SOURCE = ${JSON.stringify(bundle)};
`;
}

export function symbolModule(bundles: { collect: string; apply: string }): string {
  return `/**
 * Generated by packages/import/scripts/build-walker.ts from src/dom/symbols.ts. Don't edit by hand:
 * run \`node packages/import/scripts/build-walker.ts\` after changing it.
 *
 * Evaluating SYMBOL_COLLECT_SOURCE in a page defines \`window.__sonobeCollectSymbols(walkOptions)\`,
 * which waits for the page like the walker and resolves to its SF Symbol placeholders; evaluating
 * SYMBOL_APPLY_SOURCE defines \`window.__sonobeApplySymbols(paints)\`, which puts drawings in them.
 */

export const SYMBOL_COLLECT_SOURCE = ${JSON.stringify(bundles.collect)};

export const SYMBOL_APPLY_SOURCE = ${JSON.stringify(bundles.apply)};
`;
}
