/** esbuild bundle of the DOM walker, shared by build-walker.ts and the freshness test. */

import { build } from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

export async function bundleWalker(): Promise<string> {
  const result = await build({
    entryPoints: [path.join(root, "src/dom/entry.ts")],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: ["es2022"],
    minify: true,
    legalComments: "none",
    logLevel: "silent",
  });
  return result.outputFiles[0]!.text.trim();
}

export function walkerModule(bundle: string): string {
  return `/**
 * Generated by packages/import/scripts/build-walker.ts from src/dom/walk.ts. Don't edit by hand:
 * run \`node packages/import/scripts/build-walker.ts\` after changing the walker.
 *
 * Evaluating WALKER_SOURCE in a page defines \`window.__sonobeCapture(options)\`, which resolves to a
 * DesignCapture (see src/dom/walk.ts).
 */

export const WALKER_SOURCE = ${JSON.stringify(bundle)};
`;
}
