/** Editor state: the session, its stores, registry helpers, clipboard, edit actions, commands, and React hooks. */

export {
  createEditorSession,
  createTemplateDocument,
  DOCUMENT_TEMPLATES,
  getDefaultSession,
  setDefaultSession,
  type ConfirmDiscard,
  type DiscardChoice,
  type DocumentTemplate,
  type EditorSession,
  type EditorSessionOptions,
  type NewProjectOptions,
} from "./session.ts";
export {
  createDialogStore,
  getDefaultDialogs,
  setDefaultDialogs,
  type ChooseDialogOptions,
  type ConfirmDialogOptions,
  type DialogAction,
  type DialogKind,
  type DialogRequest,
  type DialogService,
  type DialogState,
  type DialogStore,
  type DialogVariant,
  type PickDialogItem,
  type PickDialogOptions,
  type PromptDialogOptions,
} from "./dialogs.ts";
export { BOUNDS_METHODS, createBoundsRegistry, isBoundsMethod, rectOfElement, type BoundsMethod, type BoundsProvider, type BoundsRect, type BoundsRegisterOptions, type BoundsRegistry } from "./bounds.ts";
export { createGraphGeometrySlot, type GraphGeometryNode, type GraphGeometryProvider, type GraphGeometryReply, type GraphGeometrySlot } from "./graphGeometry.ts";
export {
  assetKindFor,
  attachAssetDrop,
  createAssetDropHandlers,
  createAssetService,
  dragHasFiles,
  fileExtension,
  filesFromDataTransfer,
  probeMedia,
  type AssetDropHandlers,
  type AssetDropOptions,
  type AssetImportInput,
  type AssetImportOptions,
  type AssetImportResult,
  type AssetService,
  type AssetServiceOptions,
  type DataTransferLike,
  type DragEventLike,
  type FileLike,
  type ImportableFile,
  type MediaProbe,
} from "./assets.ts";
export { base64ToBytes, bytesToBase64, sha256Hex, sha256HexSync } from "./bytes.ts";
export {
  CLAUDE_AUTHOR,
  createDocumentStore,
  HUMAN_AUTHOR,
  normalizeAuthor,
  type ApplyInput,
  type DocumentChange,
  type DocumentChangeKind,
  type DocumentState,
  type DocumentStatus,
  type DocumentStore,
  type DocumentStoreOptions,
  type FileResult,
  type HistoryListEntry,
  type HistoryStepResult,
  type PendingExternalChange,
  type ReplaceOptions,
} from "./document.ts";
export {
  createSelectionStore,
  currentComponentId,
  hasSelection,
  isSelected,
  itemKindOf,
  selectBreadcrumbs,
  type Breadcrumb,
  type HoveredItem,
  type ItemKind,
  type PanelId,
  type RevealRequest,
  type SelectionItems,
  type SelectionState,
  type SelectionStore,
  type SelectMode,
  type Viewport,
} from "./selection.ts";
export { createPresenceStore, DEFAULT_AGENT, flashingIds, PRESENCE_FLASH_MS, workingOn, type AgentChange, type AgentChangeKind, type BeginWorkInput, type PresenceState, type PresenceStore, type WorkingItem } from "./presence.ts";
export { createConsoleStore, formatConsoleArgs, type ConsoleEntry, type ConsoleLevel, type ConsoleState, type ConsoleStore } from "./console.ts";
export {
  diagnosticsFor,
  getRegistry,
  isPatchImplemented,
  pulseOutputAddresses,
  resolveLayerOutputsIn,
  resolveLayerPropsIn,
  resolvePatchPortsIn,
  setRegistry,
  useDiagnostics,
  useLayerProps,
  useLayerTypeSpec,
  useNodePorts,
  usePatchSpec,
  useRegistry,
} from "./registry.ts";
export {
  applyPastePlan,
  CLIPBOARD_FORMAT_VERSION,
  CLIPBOARD_MIME,
  CLIPBOARD_TYPE,
  createClipboardFragment,
  MAX_CLIPBOARD_ASSET_BYTES,
  parseClipboardFragment,
  planPaste,
  SCRIPT_PATCH_TYPE,
  scriptFileOf,
  serializeClipboardFragment,
  topLevelLayerIds,
  type ClipboardCopyOptions,
  type ClipboardFragment,
  type ClipboardItems,
  type PasteOptions,
  type PasteOutcome,
  type PastePlan,
} from "./clipboard.ts";
export {
  arrangeLayers,
  copySelection,
  createComponentFromSelection,
  cutSelection,
  deleteSelection,
  duplicateSelection,
  enterSelectedComponent,
  exitComponent,
  groupSelection,
  pasteFragment,
  selectAll,
  toggleLayerLock,
  toggleLayerVisibility,
  ungroupSelection,
  type ActionResult,
  type ArrangeDirection,
  type PasteActionResult,
} from "./editActions.ts";
export { attachClipboardEvents, bindHostCommands, DESKTOP_COMMAND_MAP, registerDocumentCommands, type DocumentCommandOptions, type Notify } from "./commands.ts";
export { createDemoDocument, DEMO_DOCUMENT_NAME, demoDocumentOps } from "./demoDocument.ts";
export {
  EditorProvider,
  useConsole,
  useCurrentComponent,
  useDocument,
  useEditorSession,
  useLiveValues,
  usePresence,
  usePulseFires,
  useDialogs,
  useRuntimeState,
  useScriptTrust,
  useSelection,
  type EditorProviderProps,
} from "./EditorProvider.tsx";
