/** Editor state: the session, its stores, registry helpers, clipboard, edit actions, commands, and React hooks. */

export { createEditorSession, getDefaultSession, setDefaultSession, type ConfirmDiscard, type DiscardChoice, type EditorSession, type EditorSessionOptions } from "./session.ts";
export {
  CLAUDE_AUTHOR,
  createDocumentStore,
  HUMAN_AUTHOR,
  normalizeAuthor,
  type ApplyInput,
  type DocumentChange,
  type DocumentChangeKind,
  type DocumentState,
  type DocumentStatus,
  type DocumentStore,
  type DocumentStoreOptions,
  type FileResult,
  type HistoryListEntry,
  type HistoryStepResult,
  type PendingExternalChange,
  type ReplaceOptions,
} from "./document.ts";
export {
  createSelectionStore,
  currentComponentId,
  hasSelection,
  isSelected,
  itemKindOf,
  selectBreadcrumbs,
  type Breadcrumb,
  type HoveredItem,
  type ItemKind,
  type PanelId,
  type RevealRequest,
  type SelectionItems,
  type SelectionState,
  type SelectionStore,
  type SelectMode,
  type Viewport,
} from "./selection.ts";
export { createPresenceStore, DEFAULT_AGENT, flashingIds, PRESENCE_FLASH_MS, workingOn, type AgentChange, type AgentChangeKind, type BeginWorkInput, type PresenceState, type PresenceStore, type WorkingItem } from "./presence.ts";
export { createConsoleStore, formatConsoleArgs, type ConsoleEntry, type ConsoleLevel, type ConsoleState, type ConsoleStore } from "./console.ts";
export {
  diagnosticsFor,
  getRegistry,
  isPatchImplemented,
  pulseOutputAddresses,
  resolveLayerOutputsIn,
  resolveLayerPropsIn,
  resolvePatchPortsIn,
  setRegistry,
  useDiagnostics,
  useLayerProps,
  useLayerTypeSpec,
  useNodePorts,
  usePatchSpec,
  useRegistry,
} from "./registry.ts";
export {
  applyPastePlan,
  CLIPBOARD_FORMAT_VERSION,
  CLIPBOARD_MIME,
  CLIPBOARD_TYPE,
  createClipboardFragment,
  parseClipboardFragment,
  planPaste,
  serializeClipboardFragment,
  topLevelLayerIds,
  type ClipboardFragment,
  type PasteOptions,
  type PasteOutcome,
  type PastePlan,
} from "./clipboard.ts";
export {
  arrangeLayers,
  copySelection,
  createComponentFromSelection,
  cutSelection,
  deleteSelection,
  duplicateSelection,
  enterSelectedComponent,
  exitComponent,
  groupSelection,
  pasteFragment,
  selectAll,
  toggleLayerLock,
  toggleLayerVisibility,
  ungroupSelection,
  type ActionResult,
  type ArrangeDirection,
  type PasteActionResult,
} from "./editActions.ts";
export { attachClipboardEvents, bindHostCommands, DESKTOP_COMMAND_MAP, registerDocumentCommands, type DocumentCommandOptions, type Notify } from "./commands.ts";
export { createDemoDocument, DEMO_DOCUMENT_NAME, demoDocumentOps } from "./demoDocument.ts";
export {
  EditorProvider,
  useConsole,
  useCurrentComponent,
  useDocument,
  useEditorSession,
  useLiveValues,
  usePresence,
  usePulseFires,
  useRuntimeState,
  useSelection,
  type EditorProviderProps,
} from "./EditorProvider.tsx";
