import type { PatchCategory } from "@sonobe/core";
import {
  Braces,
  Circle,
  Code,
  Component,
  Film,
  GitBranch,
  Group,
  Image,
  Layers,
  Palette,
  PaintBucket,
  Pointer,
  Repeat,
  Scan,
  Shapes,
  Smartphone,
  Sparkle,
  Spline,
  Square,
  SquareFunction,
  TextCursorInput,
  ToggleLeft,
  Type,
  Video,
  Waypoints,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<PatchCategory, LucideIcon> = {
  interaction: Pointer,
  animation: Waypoints,
  state: ToggleLeft,
  logic: GitBranch,
  math: SquareFunction,
  loops: Repeat,
  text: Type,
  color: Palette,
  data: Braces,
  device: Smartphone,
  media: Image,
  shapes: Shapes,
  layers: Layers,
  utility: Wrench,
  components: Component,
  scripting: Code,
};

export const LAYER_ICONS: Record<string, LucideIcon> = {
  group: Group,
  rectangle: Square,
  oval: Circle,
  text: Type,
  image: Image,
  video: Video,
  shape: Spline,
  colorFill: PaintBucket,
  gradient: Sparkle,
  hitArea: Scan,
  textField: TextCursorInput,
  lottie: Film,
  shader: Code,
  clone: Layers,
  componentInstance: Component,
};
