// Measures the patch editor's node fonts in Chromium and writes the advance table that headless node
// size estimates use (packages/core/src/graph/nodeMetrics.ts): per-character widths for printable
// ASCII plus the symbols nodes show, in each font of NODE_FONTS, with the theme's --font-sans and
// --font-mono.
//
//   node apps/editor/scripts/measure-node-fonts.ts
//
// Re-run it when node fonts change (patch-editor.css, theme/tokens.css, NODE_FONTS), on macOS: the
// committed table is SF Pro Text / SF Mono, which the editor's font stacks resolve to there.
import { chromium } from "@playwright/test";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { NODE_FONTS } from "../../../packages/core/src/graph/nodeSize.ts";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "../../..");
const out = path.join(repo, "packages/core/src/graph/nodeMetrics.ts");
const tokens = readFileSync(path.join(repo, "apps/editor/src/theme/tokens.css"), "utf8");

/** Characters outside printable ASCII that node text uses: loop and live values, names, knob chips. */
const EXTRA = "×…“”—·→←āīūēōĀŪ’‘•✕♥−∞◉";

const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent(`<!doctype html><style>${tokens}</style><body></body>`);
const metrics = await page.evaluate(
  ({ fonts, extra }) => {
    const host = document.createElement("div");
    host.style.cssText = "position:absolute; left:-9999px; top:0; white-space:pre;";
    document.body.appendChild(host);
    const result: Record<string, { widths: number[]; extra: Record<string, number>; fallback: number }> = {};
    for (const [key, f] of Object.entries(fonts)) {
      const span = document.createElement("span");
      span.style.fontFamily = `var(--font-${f.family})`;
      span.style.fontSize = `${f.size}px`;
      span.style.fontWeight = String(f.weight);
      if ("italic" in f && f.italic) span.style.fontStyle = "italic";
      if ("letterSpacing" in f && f.letterSpacing) span.style.letterSpacing = `${f.letterSpacing}px`;
      host.appendChild(span);
      const width = (ch: string) => {
        span.textContent = ch.repeat(40);
        return Math.round((span.getBoundingClientRect().width / 40) * 100) / 100;
      };
      const widths: number[] = [];
      for (let c = 32; c <= 126; c++) widths.push(width(String.fromCharCode(c)));
      const symbols: Record<string, number> = {};
      for (const ch of extra) symbols[ch] = width(ch);
      const lower = widths.slice(65, 91);
      result[key] = { widths, extra: symbols, fallback: Math.round((lower.reduce((a, b) => a + b, 0) / lower.length) * 100) / 100 };
    }
    return result;
  },
  { fonts: NODE_FONTS, extra: EXTRA },
);
await browser.close();

const lines = Object.entries(metrics).map(([key, m]) => `  ${key}: { widths: [${m.widths.join(", ")}], extra: ${JSON.stringify(m.extra)}, fallback: ${m.fallback} },`);
writeFileSync(
  out,
  `// Generated by apps/editor/scripts/measure-node-fonts.ts from the editor's fonts in Chromium on macOS
// (SF Pro Text and SF Mono). Don't edit by hand.
// Advance widths in points for ASCII 32..126, plus the symbols in \`extra\`; \`fallback\` is used for other characters.

import type { NodeFont } from "./nodeSize.ts";

export interface NodeFontMetrics {
  widths: readonly number[];
  extra: Readonly<Record<string, number>>;
  fallback: number;
}

export const NODE_FONT_METRICS: Record<NodeFont, NodeFontMetrics> = {
${lines.join("\n")}
};
`,
);
console.log(`wrote ${path.relative(repo, out)} (${Object.keys(metrics).length} fonts)`);
